//THIS IS THE SCRIPT.JS FILE FOR THE
//ZWEMMER CONNOR FAN SITE
//
//PLEASE DONT ABUSE THIS CODE




//PRETTY EMPTY ISNT IT?

//...THATS BECAUSE IDK WHAT TO PUT HERE
//IM NOT A CODER OK

//PRESS CTRL+N AND TYPE 'GAY PORN' AND ENTER TO GO BACK!